package edu.upc.webservice.genero.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import edu.upc.webservice.genero.service.GeneroService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-01-20T11:27:00.110-05:00
 * Generated source version: 2.7.2
 * 
 */
@WebServiceClient(name = "GeneroServiceImplService", 
                  wsdlLocation = "http://localhost:8080/ws_cine/GeneroService?wsdl",
                  targetNamespace = "http://impl.service.genero.webservice.upc.edu/") 
public class GeneroServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.genero.webservice.upc.edu/", "GeneroServiceImplService");
    public final static QName GeneroServiceImplPort = new QName("http://impl.service.genero.webservice.upc.edu/", "GeneroServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws_cine/GeneroService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeneroServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws_cine/GeneroService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GeneroServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeneroServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneroServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GeneroService
     */
    @WebEndpoint(name = "GeneroServiceImplPort")
    public GeneroService getGeneroServiceImplPort() {
        return super.getPort(GeneroServiceImplPort, GeneroService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneroService
     */
    @WebEndpoint(name = "GeneroServiceImplPort")
    public GeneroService getGeneroServiceImplPort(WebServiceFeature... features) {
        return super.getPort(GeneroServiceImplPort, GeneroService.class, features);
    }

}
