package edu.upc.webservice.genero.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-01-20T11:27:00.102-05:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://service.genero.webservice.upc.edu/", name = "GeneroService")
@XmlSeeAlso({ObjectFactory.class})
public interface GeneroService {

    @WebResult(name = "save", targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://service.genero.webservice.upc.edu/", className = "edu.upc.webservice.genero.service.Save")
    @WebMethod
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.genero.webservice.upc.edu/", className = "edu.upc.webservice.genero.service.SaveResponse")
    public int save(
        @WebParam(name = "arg0", targetNamespace = "")
        edu.upc.webservice.genero.service.Genero arg0
    );

    @WebResult(name = "delete", targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.genero.webservice.upc.edu/", className = "edu.upc.webservice.genero.service.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.genero.webservice.upc.edu/", className = "edu.upc.webservice.genero.service.DeleteResponse")
    public int delete(
        @WebParam(name = "arg0", targetNamespace = "")
        edu.upc.webservice.genero.service.Genero arg0
    );

    @WebResult(name = "update", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://service.genero.webservice.upc.edu/", className = "edu.upc.webservice.genero.service.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.genero.webservice.upc.edu/", className = "edu.upc.webservice.genero.service.UpdateResponse")
    public int update(
        @WebParam(name = "arg0", targetNamespace = "")
        edu.upc.webservice.genero.service.Genero arg0
    );

    @WebResult(name = "getGenero", targetNamespace = "")
    @RequestWrapper(localName = "getGenero", targetNamespace = "http://service.genero.webservice.upc.edu/", className = "edu.upc.webservice.genero.service.GetGenero")
    @WebMethod
    @ResponseWrapper(localName = "getGeneroResponse", targetNamespace = "http://service.genero.webservice.upc.edu/", className = "edu.upc.webservice.genero.service.GetGeneroResponse")
    public edu.upc.webservice.genero.service.Genero getGenero(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebResult(name = "getAll", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://service.genero.webservice.upc.edu/", className = "edu.upc.webservice.genero.service.GetAll")
    @WebMethod
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://service.genero.webservice.upc.edu/", className = "edu.upc.webservice.genero.service.GetAllResponse")
    public java.util.List<edu.upc.webservice.genero.service.Genero> getAll();
}
