
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.upc.webservice.genero.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-01-20T11:27:00.080-05:00
 * Generated source version: 2.7.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "GeneroServiceImplService",
                      portName = "GeneroServiceImplPort",
                      targetNamespace = "http://impl.service.genero.webservice.upc.edu/",
                      wsdlLocation = "http://localhost:8080/ws_cine/GeneroService?wsdl",
                      endpointInterface = "edu.upc.webservice.genero.service.GeneroService")
                      
public class GeneroServiceImpl implements GeneroService {

    private static final Logger LOG = Logger.getLogger(GeneroServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see edu.upc.webservice.genero.service.GeneroService#save(edu.upc.webservice.genero.service.Genero  arg0 )*
     */
    public int save(edu.upc.webservice.genero.service.Genero arg0) { 
        LOG.info("Executing operation save");
        System.out.println(arg0);
        try {
            int _return = 1928255943;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.upc.webservice.genero.service.GeneroService#delete(edu.upc.webservice.genero.service.Genero  arg0 )*
     */
    public int delete(edu.upc.webservice.genero.service.Genero arg0) { 
        LOG.info("Executing operation delete");
        System.out.println(arg0);
        try {
            int _return = 1866934503;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.upc.webservice.genero.service.GeneroService#update(edu.upc.webservice.genero.service.Genero  arg0 )*
     */
    public int update(edu.upc.webservice.genero.service.Genero arg0) { 
        LOG.info("Executing operation update");
        System.out.println(arg0);
        try {
            int _return = -1211327378;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.upc.webservice.genero.service.GeneroService#getGenero(java.lang.Integer  arg0 )*
     */
    public edu.upc.webservice.genero.service.Genero getGenero(java.lang.Integer arg0) { 
        LOG.info("Executing operation getGenero");
        System.out.println(arg0);
        try {
            edu.upc.webservice.genero.service.Genero _return = new edu.upc.webservice.genero.service.Genero();
            _return.setDescripcion("Descripcion-1729661832");
            _return.setEstado(Integer.valueOf(-1313597906));
            _return.setFechaCreacion(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-01-20T11:27:00.099-05:00"));
            _return.setFechaModificacion(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-01-20T11:27:00.099-05:00"));
            _return.setIdGenero(Integer.valueOf(-163587401));
            _return.setUsuarioCreacion(Integer.valueOf(854766510));
            _return.setUsuarioModificacion(Integer.valueOf(-1750039411));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edu.upc.webservice.genero.service.GeneroService#getAll(*
     */
    public java.util.List<edu.upc.webservice.genero.service.Genero> getAll() { 
        LOG.info("Executing operation getAll");
        try {
            java.util.List<edu.upc.webservice.genero.service.Genero> _return = new java.util.ArrayList<edu.upc.webservice.genero.service.Genero>();
            edu.upc.webservice.genero.service.Genero _returnVal1 = new edu.upc.webservice.genero.service.Genero();
            _returnVal1.setDescripcion("Descripcion-387519636");
            _returnVal1.setEstado(Integer.valueOf(941167282));
            _returnVal1.setFechaCreacion(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-01-20T11:27:00.101-05:00"));
            _returnVal1.setFechaModificacion(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-01-20T11:27:00.101-05:00"));
            _returnVal1.setIdGenero(Integer.valueOf(-468960930));
            _returnVal1.setUsuarioCreacion(Integer.valueOf(-1828797453));
            _returnVal1.setUsuarioModificacion(Integer.valueOf(-1061845693));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
